"""
Streamlit UI for the Financial Analytics Agent.

Ask a natural-language question about stocks and markets. The app shows:
- The agent's reasoning trace (which steps ran, what decisions were made)
- The generated SQL query
- Query results as an interactive table
- A provenance footer (source tables, data freshness, currency, coverage)

Run with:  streamlit run app/streamlit_app.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st

# Ensure project root is on the path so agent/ and semantic_layer/ resolve
PROJECT_ROOT = Path(__file__).parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from agent.orchestrator import AnalyticsAgent, DEFAULT_DB_PATH
from agent.response_formatter import AgentResponse

# ── Page config ──────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="Financial Analytics Agent",
    page_icon="📊",
    layout="wide",
)

# ── Helper rendering functions ───────────────────────────────────────────────


def _render_trace(trace: list[dict]) -> None:
    """Render the agent's reasoning trace as a step-by-step timeline."""

    step_labels = {
        "clarify": ("1. Clarify", "Interpreted the question"),
        "resolve": ("2. Resolve", "Checked the semantic layer"),
        "query": ("3. Query", "Generated SQL"),
        "review": ("4. Review", "Adversarial review"),
        "execute": ("5. Execute", "Ran query against DuckDB"),
    }

    for step_data in trace:
        step_name = step_data.get("step", "unknown")
        label, description = step_labels.get(step_name, (step_name.title(), ""))

        with st.expander(f"**{label}** — {description}", expanded=False):
            if step_name == "clarify":
                interpreted = step_data.get("interpreted", "")
                metric_type = step_data.get("metric_type", "")
                error = step_data.get("error")
                if error:
                    st.warning(f"LLM clarification unavailable: {error}")
                if interpreted:
                    st.markdown(f"**Interpreted as:** {interpreted}")
                if metric_type:
                    st.markdown(f"**Metric type:** `{metric_type}`")

            elif step_name == "resolve":
                found = step_data.get("found", False)
                metric = step_data.get("metric")
                candidates = step_data.get("candidates", [])
                if found:
                    st.success(f"Semantic layer hit: `{metric}`")
                else:
                    st.warning("No governed metric found — falling through to LLM generation")
                if candidates:
                    st.markdown(f"**Candidates considered:** {', '.join(f'`{c}`' for c in candidates)}")

            elif step_name == "query":
                source = step_data.get("source", "")
                if source == "semantic_layer":
                    st.success(f"SQL compiled from semantic layer metric: `{step_data.get('metric', '')}`")
                elif source == "llm_generated":
                    ref = step_data.get("reference", "none")
                    st.info(f"SQL generated by LLM (reference doc: `{ref}`)")
                    preview = step_data.get("reasoning_preview", "")
                    if preview:
                        st.text(preview)

            elif step_name == "review":
                passed = step_data.get("passed", True)
                issues = step_data.get("issues", 0)
                summary = step_data.get("summary", "")
                if passed:
                    st.success(f"Review passed. {summary}")
                else:
                    st.error(f"Review found {issues} issue(s). {summary}")

            elif step_name == "execute":
                success = step_data.get("success", False)
                rows = step_data.get("rows", 0)
                if success:
                    st.success(f"Query returned {rows} row(s)")
                else:
                    st.error("Query execution failed")


def _render_provenance(provenance) -> None:
    """Render the provenance footer as a compact row of metrics."""
    cols = st.columns(5)

    with cols[0]:
        st.metric("Source", ", ".join(provenance.source_tables) if provenance.source_tables else "—")
    with cols[1]:
        st.metric("Freshness", provenance.data_freshness or "—")
    with cols[2]:
        st.metric("Currency", provenance.currency or "—")
    with cols[3]:
        st.metric("Coverage", provenance.coverage or "—")
    with cols[4]:
        st.metric("Metric Source", provenance.metric_source or "—")

    if provenance.review_summary:
        st.caption(f"Review: {provenance.review_summary}")


# ── Sidebar ──────────────────────────────────────────────────────────────────

with st.sidebar:
    st.title("Financial Analytics Agent")
    st.caption(
        "Ask natural-language questions about stocks, returns, risk, "
        "and more. Powered by a governed semantic layer and Claude."
    )

    st.divider()

    st.subheader("Configuration")
    db_path = st.text_input(
        "DuckDB warehouse path",
        value=str(DEFAULT_DB_PATH),
        help="Path to the warehouse.duckdb file built by ingest_prices.py",
    )
    review_enabled = st.toggle("Enable adversarial review", value=True)

    st.divider()

    st.subheader("Available tickers")
    col1, col2 = st.columns(2)
    with col1:
        st.markdown(
            "**US equities**\n\n"
            "AAPL, MSFT, GOOGL, AMZN, NVDA, META, TSLA, JPM, V, "
            "JNJ, PG, UNH, HD, MA, PFE"
        )
    with col2:
        st.markdown(
            "**Oslo Bors**\n\n"
            "EQNR.OL, DNB.OL, MOWI.OL, ORK.OL, TEL.OL, AKRBP.OL\n\n"
            "**Indices**\n\n"
            "^GSPC, ^OEX, ^IXIC"
        )

    st.divider()

    st.subheader("Available metrics")
    st.markdown(
        "cumulative_return, annualized_volatility, sharpe_ratio, "
        "sortino_ratio, max_drawdown, beta, correlation, "
        "average_daily_volume, vwap, price_range"
    )

    st.divider()
    st.caption("Built with the [4-layer analytics stack](https://www.anthropic.com/engineering/analytics-with-claude) architecture.")


# ── Agent setup ──────────────────────────────────────────────────────────────

@st.cache_resource
def get_agent(db_path: str, review_enabled: bool) -> AnalyticsAgent:
    return AnalyticsAgent(db_path=db_path, review_enabled=review_enabled)


# ── Example questions ────────────────────────────────────────────────────────

EXAMPLES = [
    "What was AAPL's Sharpe ratio in 2024?",
    "Compare the cumulative returns of MSFT and GOOGL in Q1 2024",
    "What is the beta of TSLA relative to the S&P 500 in 2024?",
    "Which stock had the highest annualized volatility in 2024?",
    "What is the correlation between EQNR.OL and DNB.OL in 2024?",
    "How did the S&P 500 perform in 2024?",
    "What was NVDA's maximum drawdown in 2024?",
]


# ── Main UI ──────────────────────────────────────────────────────────────────

st.header("Ask a question")

# Example question chips
selected_example = None
cols = st.columns(4)
for i, example in enumerate(EXAMPLES[:4]):
    with cols[i]:
        if st.button(example[:45] + "..." if len(example) > 45 else example, key=f"ex_{i}", use_container_width=True):
            selected_example = example

if len(EXAMPLES) > 4:
    cols2 = st.columns(4)
    for i, example in enumerate(EXAMPLES[4:]):
        with cols2[i]:
            if st.button(example[:45] + "..." if len(example) > 45 else example, key=f"ex2_{i}", use_container_width=True):
                selected_example = example

question = st.text_input(
    "Your question",
    value=selected_example or "",
    placeholder="e.g., What was the Sharpe ratio of AAPL vs MSFT in 2024?",
    label_visibility="collapsed",
)

if question:
    agent = get_agent(db_path, review_enabled)

    with st.spinner("Processing..."):
        try:
            response: AgentResponse = agent.answer(question)
        except Exception as e:
            st.error(f"Agent error: {e}")
            st.stop()

    # ── Answer ───────────────────────────────────────────────────────────
    st.subheader("Answer")
    st.markdown(response.answer)

    if response.methodology:
        st.caption(response.methodology)

    # ── Warnings ─────────────────────────────────────────────────────────
    if response.warnings:
        with st.expander(f"Warnings ({len(response.warnings)})", expanded=False):
            for w in response.warnings:
                st.warning(w, icon="⚠️")

    # ── Results, SQL, Trace tabs ─────────────────────────────────────────
    tab_results, tab_sql, tab_trace = st.tabs(["Results", "SQL", "Reasoning Trace"])

    with tab_results:
        if response.data is not None and not response.data.empty:
            st.dataframe(response.data, use_container_width=True, hide_index=True)
        else:
            st.info("No data returned.")

    with tab_sql:
        if response.sql:
            st.code(response.sql, language="sql")
        else:
            st.info("No SQL generated.")

    with tab_trace:
        if response.trace:
            _render_trace(response.trace)
        else:
            st.info("No trace available.")

    # ── Provenance footer ────────────────────────────────────────────────
    if response.provenance:
        st.divider()
        _render_provenance(response.provenance)
